### ISSUE TITLE
TypeError: Cannot read property 'observation_location' of undefined

### ISSUE THREAD

**Issue by E3V3A** [cowboysdude/MMM-NOAA#23]
Been running you older version for quite some time, but today I found my MM didn't respond and checked my err logs to find:
```
TypeError: Cannot read property 'observation_location' of undefined
    at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-NOAA/node_helper.js:26:49)
    at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
```

**Comment by cowboysdude** [comment]
HUH go to our forum I just posted it......try that one..... if you want V1 I'll post V2 on there tonight

**Comment by cowboysdude** [comment]
Once in a while this is happens.   For some reason the data does not transfer quick enough etc... :)
